version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  app: 
    image: rsoi-1
    container_name: app
    restart: unless-stopped
    environment:
      RSOI1_PORT: 8888
      RSOI1_STORAGE_CONN_STRING: "postgresql://postgres:postgres@postgres:5432/postgres"
    ports: 
      - "8888:8888"

volumes:
  db-data: